### PR TITLE
Generate ES5

### PR DESCRIPTION
**Pull request by lbodor**

### CODE REVIEW

**Comment by lbodor** [comment]
Closing, wrong fork.

**Comment by midknight41** [comment]
@lbodor I've removed the deprecated one now if that was the reason for the fork. Fixed with #47 and shipped with 2.0.2.

**Comment by midknight41** [comment]
@lbodor Ha. I've just noticed this generates ES5 code which I didn't really mean to do. Are you using this in the browser?

**Comment by lbodor** [comment]
Yes. That's why I thought I would make this change in my own fork. With this change it works fine in the browser.

**Pull request closed without merging**
