### PR TITLE
[better type definition file]

### PR DESCRIPTION
**Pull request by singhs020**
Completing the type def file for IDE suggestion support and usage in typescript projects

### CODE REVIEW

**Comment by singhs020** [comment]
@jmac105 Please have a look. we will need to publish a patch version to make it work.

**Comment by jmac105** [comment]
Sorry @singhs020 I totally missed the email notification for this...

**Comment by jmac105** [comment]
Hey @singhs020 ... thought I had permission to publish this on npm but apparently not! I've run `npm run patch`, it's pushed a new version to the repo along with the new tag so you just need to run `npm publish` please!!

**Comment by singhs020** [comment]
Hey @jmac105 , thanks for merging it. Unfortunately i also don't have permission to publish the package.

**Pull request merged**
